name: Continuous Integration

on: [push]

env:
  CI: true

permissions:
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Setup Node (v${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile

  format:
    name: Format
    runs-on: ${{ matrix.os }}
    steps:
      - run: pnpm --if-present format

  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
      - run: pnpm --if-present lint
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - run: pnpm --if-present test

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - run: pnpm --if-present build
